config/routes.rb
NickRay::Application.routes.draw do
  root 'films#index'

  resources :films

end

app/models/film.rb
class Film < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def index
	end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
	def index
		@films = Film.all
	end

	def new
		@film = Film.new
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/films/index.html.erb
<% @films.each do |film| %>
	<div>
		<h1><%= film.movie %></h1><br />
		<i><%= film.year %></i><br />
	</div>

<% end %>

app/views/films/new.html.erb
<h1>Enter Nick Ray film details</h1>
<%= simple_form_for @film do |f| %>
	<%= f.input :movie %>
	<%= f.input :year %>
	<%= f.submit 'Create', :class => 'btn btn-danger' %>
<% end %>

app/views/films/show.html.erb
<% @films.each do |film| %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nicholas Ray!</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
 
</head>
<body>
	 Nicholas Ray filmography
	 <%= link_to 'Add Film', new_film_path %>
<%= yield %>

</body>
</html>

app/views/notes/index.html.erb
	<h1 ></h1>

	<p>  

	</p>